version: "3"
services:
  db:
    container_name: pg_container
    hostname: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trans
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    depends_on:
      - db
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    # image: tusharchy/nest-and-postgres-application:latest
    environment:
      - DB_TYPE=postgres
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DB=trans
      - POSTGRES_SYNC=true
      # - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_PORT=5432
      - APP_EXPIRES=3600
      - APP_PORT=3000
    ports:
      - "3001:3001" # expose-to-the-world : only-in-the-docker
    container_name: nest-todo-app-be
    depends_on:
      - db
      - pgadmin
    volumes:
      - ./back:/app
      - /app/node_modules

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #   - 8080:8080
  #   networks:
  #     - backend
  #   volumes:
  #    - ./frontend:/app
  #   env_file:
  #     - ./env/front.env
  #   restart: unless-stopped
  #   depends_on:
  #     - backend

  # adminer:
  #   image: adminer
  #   ports:
  #     - '8080:8080'
